[2025-03-03T15:52:06.283+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dvc_pipeline_V2.performance_drift_monitoring manual__2025-03-03T15:51:08.515381+00:00 [queued]>
[2025-03-03T15:52:06.304+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dvc_pipeline_V2.performance_drift_monitoring manual__2025-03-03T15:51:08.515381+00:00 [queued]>
[2025-03-03T15:52:06.305+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T15:52:06.323+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): performance_drift_monitoring> on 2025-03-03 15:51:08.515381+00:00
[2025-03-03T15:52:06.332+0000] {standard_task_runner.py:60} INFO - Started process 183 to run task
[2025-03-03T15:52:06.340+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dvc_pipeline_V2', 'performance_drift_monitoring', 'manual__2025-03-03T15:51:08.515381+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/new_dag.py', '--cfg-path', '/tmp/tmpb9mcvh94']
[2025-03-03T15:52:06.344+0000] {standard_task_runner.py:88} INFO - Job 114: Subtask performance_drift_monitoring
[2025-03-03T15:52:06.368+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-03T15:52:06.424+0000] {task_command.py:423} INFO - Running <TaskInstance: dvc_pipeline_V2.performance_drift_monitoring manual__2025-03-03T15:51:08.515381+00:00 [running]> on host 99d7c207cb9e
[2025-03-03T15:52:06.611+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dvc_pipeline_V2' AIRFLOW_CTX_TASK_ID='performance_drift_monitoring' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T15:51:08.515381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T15:51:08.515381+00:00'
[2025-03-03T15:52:06.615+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T15:52:06.616+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', ['python /opt/***/src/data/performance_drift_monitoring.py']]
[2025-03-03T15:52:06.618+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 203, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    self.sub_process = Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1655, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not list
[2025-03-03T15:52:06.633+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dvc_pipeline_V2, task_id=performance_drift_monitoring, execution_date=20250303T155108, start_date=20250303T155206, end_date=20250303T155206
[2025-03-03T15:52:06.661+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 114 for task performance_drift_monitoring (expected str, bytes or os.PathLike object, not list; 183)
[2025-03-03T15:52:06.706+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-03T15:52:06.765+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
